<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT c 
                            FROM AppBundle:Category c
                            WHERE c.parent IS NULL');
        return $query->getResult();
    }

    public function findSubCategories($category)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT c 
                            FROM AppBundle:Category c
                            WHERE c.parent = :category');

        $query->setParameter('category', $category);

        return $query->getResult();
    }
}

